### ISSUE TITLE
Provide an option to avoid format guesser

### ISSUE THREAD

**Issue by robertzk** [hadley/lubridate#308]
Maybe we could give all the parsing functions that rely on the guesser an additional option to use a full scan, with the user knowing it will impact performance? This will avoid issues like https://github.com/hadley/lubridate/issues/307

**Comment by vspinu** [comment]
:+1 

- Add `train` option to `parse_date_time` and make no-training the default. 
- Ignore training option when only one order has been supplied.

**Comment by peterhurford** [comment]
:+1:

**Comment by vspinu** [comment]
I am afraid it's not possible to avoid sparse guesser because of the flexibility of the "orders" versus the `sprtime` "formats". When you supply `ymd` it can match "12-12-12" or "2012-12-12"  or "121212" etc. You cannot solve that without training. So I am afraid you just have to use alternative functions (`sptrtime`, `fast_sptrtime` or `parse_date_time2`) that don't perform guessing. 

I have now documented this in the `parse_date_time` documentation.

**Comment by vspinu** [comment]
I came back on this one. There is now an option `exact=TRUE` that treats `orders` as `strptime` formats and doesn't perform any training or guessing.

**Comment by peterhurford** [comment]
:+1: Awesome!

**Comment by vspinu** [comment]
In next version `parse_date_time` gained `train=TRUE` and `drop=FALSE` arguments. As you could guess, formats are no longer dropped. Similar issues should not occur anymore.
