### ISSUE TITLE
`ymd_hms` functions are not picking PM/AM indicator

### ISSUE THREAD

**Issue by vspinu** [hadley/lubridate#327]
```
> mdy_hms(c('12/17/1996 04:00:00 PM'))
[1] "1996-12-17 04:00:00 UTC"
> ymd_hms(c('1996/04/01 04:00:00 PM'))
[1] "1996-04-01 04:00:00 UTC"
> 
```

**Comment by vspinu** [comment]
This happens on English locales that don't have PM/AM indicator like `LC_TIME=en_DK.UTF-8` that I have. 

Two ways to deal with it. 

First option is introduce mandatory english locale parsing that would have lower priority than the current locale. This would essentially double the current overhead and it's also not system independent. You will have to know how standard english locales are names on all OSes. I am not even sure this is possible.

Second option is to deal with AM/PM and day/month english names explicitly at c-parser level. This is directly related to  #287. I think this is the most robust, fast and simplest approach.

**Comment by dracodoc** [comment]
It also happened on me with Chinese locales. I [solved my problem](http://stackoverflow.com/a/33452653/3718827) with `Sys.setlocale("LC_TIME", "C")` after hours fight and search.

I think this problem should be solved by user with either setting locale temporally in one session or specify locale in parsing command.

However it will help a lot if the error messages and function documents include information and examples like this(especially the more obvious set locale to `English` often not working). I believe this problem is actually quite common: there are many people using system locale other than English but need to read time format in English.

`data.table` documents included many examples and even StackOverflow discussion links, I think that really helped.
