### ISSUE TITLE
parsing works on numeric but not on string

### ISSUE THREAD

**Issue by dracodoc** [hadley/lubridate#339]
For certain cases, numeric input can be parsed correctly, but the string format of same input cannot be parsed.

    parse_date_time("2202011", "mdy")
    #> [1] NA
    #> Warning message:
    #> All formats failed to parse. No formats found. 

    parse_date_time(2202011, "mdy")
    #>[1] "2011-02-20 UTC"

    mdy("2202011")
    #>[1] NA

    mdy(2202011)
    #>[1] "2011-02-20 UTC"

They worked on some other simpler inputs:

    mdy("010210")
    #>[1] "2010-01-02 UTC"

    mdy(010210)
    #>[1] "2010-01-02 UTC"

**Comment by vspinu** [comment]
It works for numeric because numbers (after conversion to character) which have odd number of characters are automatically prefixed with 0.  Something along this lines in principle could be done for characters but I am not sure it's worth an effort. You can simply `paste0` yourself or convert to integer and then `mdy` it.

What is your use case more concretely?

**Comment by dracodoc** [comment]
I was reading NFIRS data on fire incident which were DBF files. The DBF file save dates in this format. I could just use numeric format without problem, I just thought there could be something wrong if the parsing works on numeric but not on characters, since the parsing should be working on characters anyway.

So this may not be a real problem, just something caught me on surprise.

**Comment by vspinu** [comment]
I don't see how to fix this without imposing an overhead of all-digit grep.  I think instances like yours are pretty rare, so I am inclined to leave it as it is.  It an example of high level consistent inconsistency of the UI. Users like yourself will quickly figure out what is what.
