### ISSUE TITLE
implement unlist for intervals and periods

### ISSUE THREAD

**Issue by mgacc0** [hadley/lubridate#350]
Could you please implement the `unlist` method for Interval and Period classes?

``` R
ints <- c(
  new_interval(ymd("2001-01-01"), ymd("2002-01-01")),
  new_interval(ymd("2001-01-01"), ymd("2004-01-01"))
)

unlist(as.list(ints))
# [1] 31536000 94608000

unlist( Map(function(x) as.period(x, "days"), ints) )
# [1] 0 0
```

(Thanks!)

**Comment by vspinu** [comment]
Unlist is not generic by default and is a very efficient function which is often used in conjunction with `lapply`. Making it generic would imply imposing an additional overhead. 

Why do you need it? interval objects or periods are not lists. So this doesn't make much sense. Your particular use case is rather non-standard.

**Comment by mgacc0** [comment]
For my particular use case, I could do it without using lists.
I just thought it could be interesting not to lose information when doing `unlist`:
```R
l <- Map(function(x) as.period(x, "days"), ints)
l
# [[1]]
#[1] "365d 0H 0M 0S"
#  
# [[2]]
# [1] "1095d 0H 0M 0S"

unlist( l )
# [1] 0 0
```

**Comment by vspinu** [comment]
I think this is actually a bug in R, feel free to report. `unlist` should not unclass the underlying S4 object.

**Comment by vspinu** [comment]
> Unlist is not generic by default 

I was wrong. It's actually an "internal generic"

**Comment by mgacc0** [comment]
Ok:  https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16558

**Comment by lawremi** [comment]
Not really solved. The only change in R 3.3 is that it will be possible to define S4 methods on `unlist` without an explicit `unlist` generic. There is no way to dispatch on an ordinary list that happens to contain Period objects. This applies to both S3 and S4. For that, you would need a special class PeriodList, and you would need to cast the output of `Map()` to that. As an alternative, `do.call(c, unname(listOfPeriods))` would work. Note the `unname` is needed for S4 dispatch to work reliably, due to the weirdness of the internal `c` generic. I will think about whether `unlist` could be made smart enough to essentially do `do.call(c, ...)` automatically... but for now that's how it is.

**Comment by vspinu** [comment]
Thanks Michael for clarification. 

> I will think about whether unlist could be made smart enough to essentially do do.call(c, ...) automatically

That would be great, indeed.
