### ISSUE TITLE
year() can get confused by a leap year

### ISSUE THREAD

**Issue by ellisp** [hadley/lubridate#398]
I'm not sure exactly what the desired behaviour is for "two years before 29 February 2016" - it could be either 28 February 2014 or 1 March 2014.  Perhaps it is deliberately undefined, in which case it should probably be documented?  If not deliberate, it should return one or the other:
```
> as.Date("2016-02-29") - years(2)
[1] NA
> as.Date("2016-02-29") + days(1) - years(2) - days(1)
[1] "2014-02-28"
```
Thanks @LarryZhang2016 for spotting this.

**Comment by vspinu** [comment]
This is documented in `Period-class`. Arithmetics with periods is not associative.  

The first example or yours is the most FAQ and is by design. See documentation for ‘%m+%’ and ‘add_with_rollback’. Second one happens because of natural precedence order of operators. You add one day and operate on 1st of March.
