### ISSUE TITLE
Deprecate here()?

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#436]
Or at least document why it's needed as well as `now()`.

(I think it would be reasonable to document `today()` and `now()` in the same file)

**Comment by vspinu** [comment]
Makes sense. I wasn't even aware of `here`.

**Comment by FabianRoger** [comment]
`here()` has been depreciated but is still loaded. This means there is a name conflict with the `here`function from the  [`here` package](https://github.com/jennybc/here_here). This is especially annoying as the here package is used to construct relative paths and is therefore loaded in almost every script. Of cause the problem is solved when lubridate is loaded before the here package or `here` is called explicitly via `here::here` but as the `lubridate::here` function is depreciated anyways I was wondering whether there are any plans to remove it completely?
