### ISSUE TITLE
`duration` ignores class of first argument

### ISSUE THREAD

**Issue by klmr** [hadley/lubridate#462]
See [:link: Stack Overflow question](http://stackoverflow.com/q/39163160/1968).

In a nutshell, the following code

```r
time = now()
five_sec = interval(time, time + 5)
duration(five_sec)
# [1] "5s"
duration(five_sec, units = 'days')
# [1] "432000s (~5 days)"
```

Yields an unexpected output for the last line because the class of `five_sec` is ignored, and its unit is overridden to be interpreted as `days`. This makes sense for a unitless `num` argument — but `five_sec` isn’t unitless by virtue of being an `Interval`.

The expected behaviour is that this should be disallowed — i.e. throw an error, or at least signal a stern warning that the interval’s unit is being ignored.

**Comment by Christoph999** [comment]
I thought the result is transferred to the specified `unit`. In the case above 5/(24*3600). In case of years (which can have 365 or 366 days) this feature is really helpful.

**Comment by vspinu** [comment]
Yes. It should be disallowed. For conversion use `as.duration`.

**Comment by Christoph999** [comment]
Thank you. Perhaps you can add a comment somewhere that for conversion you 
need 

as.numeric(as.duration(i1), units = "days")
or
as.numeric(i1, units = 'days')# Throwing a message on my computer - I 
don't know the reason.

I could not find it in the descrition nor in the article "Dates and Times 
Made Easy with lubridate"...


Der digitale Crash-Test
Virtuell gegen die Wand gefahren  

Einladung zum 10. Simulation Day
5. Sept 2016, 18:00,  FHZ St.Gallen
Einladung und Anmeldung



Von:    Vitalie Spinu <notifications@github.com>
An:     hadley/lubridate <lubridate@noreply.github.com>
Kopie:  Christoph Strauss <christoph.strauss@fhsg.ch>, Comment 
<comment@noreply.github.com>
Datum:  26.08.2016 13:07
Betreff:        Re: [hadley/lubridate] `duration` ignores class of first 
argument (#462)



Yes. It should be disallowed. For conversion use as.duration.
?
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




________________________________________________________________

Dr. Christoph Strauss
Projektleiter

Fon +41 71 226 12 29
Web http://www.fhsg.ch

FHS St.Gallen, Hochschule für Angewandte Wissenschaften
Institut IMS-FHS |  

FHO Fachhochschule Ostschweiz

**Comment by vspinu** [comment]
Hm. I am starting thinking this was a mistake. There might be plenty of derived classes from numeric that are valid inputs into `duration` constructor. The fact that lubridate's interval and period inherit from numeric was a mistake. It might be changed some day. 

I am replacing this change with a much weaker check for "Period" and "Interval" class.

**Comment by vspinu** [comment]
> as.numeric(i1, units = 'days')# Throwing a message on my computer - I don't know the reason.

Not anymore in the development version of lubridate.
