### ISSUE TITLE
adding months to the 31st

### ISSUE THREAD

**Issue by paparaka** [hadley/lubridate#495]
I have experience a strange bug which is much easier to show than explain:
`"2016-03-31" %>% ymd + months(3)`
result in a NA, because June doesn't have 31 days.

I expecting to get 2016-06-30.
Is this a lubridate bug or just bad coding?

**Comment by cderv** [comment]
Hi, 
It is by design. 
Look at the end of the [vignette](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html) the part on **Arithmetic with date times**, under **If anyone drove a time machine, they would crash**. It is explained there why. 

You could have the results you want with `%m+%` instead of `+` normally.

**Comment by vspinu** [comment]
See `%m+` and `add_with_rollback` for a different behavior.
