### ISSUE TITLE
ymd() differences of characters and numeric input. Bug?

### ISSUE THREAD

**Issue by Tazinho** [hadley/lubridate#521]
Is this intended behaviour?

> ymd(00010101)
[1] "2001-01-01"
> ymd("00010101")
[1] "0001-01-01"

**Comment by vspinu** [comment]
What is 00010101?   Leading 0s are meaningless for numeric input. R allows that but there is no way for lubridate to detect that you input those in, so you get what you get from 10101. It's the same as 

```R
> ymd("010101")
[1] "2001-01-01"
> 
```

because lubridate internally completes even numbers with even number of digits with a leading 0.

**Comment by Tazinho** [comment]
Yes, but if you allow integer/double as input, this is somehow inconsistent.
See for example

> lubridate::ymd(00990101)
[1] "1999-01-01"
> lubridate::ymd(01000101)
[1] "0100-01-01"

**Comment by vspinu** [comment]
Where exactly do you see inconsistency? Leading 0s are dropped, so you should ignore those in numeric input.  It might appear as inconsistency but there is nothing that we can do about it for technical reasons.

The decision was made to interpret yy-01-01 as 19yy for all yy > 69 and 20yy for all others for consistency with base R.

**Comment by Tazinho** [comment]
Don't know if I like that decision, but at least it's superclear now. Thanks!
